// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
	AcknowledgeAlertData,
	AcknowledgeAlertErrors,
	AcknowledgeAlertResponses,
	DeleteApiKeyData,
	DeleteApiKeyErrors,
	DeleteApiKeyResponses,
	GetAlertGroupsData,
	GetAlertGroupsErrors,
	GetAlertGroupsResponses,
	GetAlertHistoryData,
	GetAlertHistoryErrors,
	GetAlertHistoryResponses,
	GetAlertsData,
	GetAlertsErrors,
	GetAlertsResponses,
	GetConfigData,
	GetConfigErrors,
	GetConfigResponses,
	GetRequiredFilesData,
	GetRequiredFilesErrors,
	GetRequiredFilesResponses,
	GetRoutingTreeData,
	GetRoutingTreeErrors,
	GetRoutingTreeResponses,
	GetSilenceData,
	GetSilenceErrors,
	GetSilenceResponses,
	GetSilencesData,
	GetSilencesErrors,
	GetSilencesResponses,
	GetStatsData,
	GetStatsErrors,
	GetStatsResponses,
	GetUserData,
	GetUserErrors,
	GetUserResponses,
	GetUserTokensData,
	GetUserTokensErrors,
	GetUserTokensResponses,
	PostAlertCommentData,
	PostAlertCommentErrors,
	PostAlertCommentResponses,
	PostAlertsData,
	PostAlertsErrors,
	PostAlertsResponses,
	PostApiKeyData,
	PostApiKeyErrors,
	PostApiKeyResponses,
	PostConfigData,
	PostConfigErrors,
	PostConfigResponses,
	PostRequiredFilesData,
	PostRequiredFilesErrors,
	PostRequiredFilesResponses,
	PostSilenceData,
	PostSilenceErrors,
	PostSilenceResponses,
} from "./types.gen";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
	TData,
	ThrowOnError
> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

/**
 * Get a list of alerts
 */
export const getAlerts = <ThrowOnError extends boolean = false>(options?: Options<GetAlertsData, ThrowOnError>) => {
	return (options?.client ?? client).get<GetAlertsResponses, GetAlertsErrors, ThrowOnError>({
		url: "/api/v2/alerts",
		...options,
	});
};

/**
 * Add alerts to the system
 */
export const postAlerts = <ThrowOnError extends boolean = false>(options?: Options<PostAlertsData, ThrowOnError>) => {
	return (options?.client ?? client).post<PostAlertsResponses, PostAlertsErrors, ThrowOnError>({
		url: "/api/v2/alerts",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Get a set of statistics
 */
export const getStats = <ThrowOnError extends boolean = false>(options: Options<GetStatsData, ThrowOnError>) => {
	return (options.client ?? client).get<GetStatsResponses, GetStatsErrors, ThrowOnError>({
		url: "/api/v2/{resourceType}/stats",
		...options,
	});
};

/**
 * Get a list of alert groups
 */
export const getAlertGroups = <ThrowOnError extends boolean = false>(
	options?: Options<GetAlertGroupsData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<GetAlertGroupsResponses, GetAlertGroupsErrors, ThrowOnError>({
		url: "/api/v2/alerts/groups",
		...options,
	});
};

/**
 * Acknowledge a firing alert
 */
export const acknowledgeAlert = <ThrowOnError extends boolean = false>(
	options: Options<AcknowledgeAlertData, ThrowOnError>,
) => {
	return (options.client ?? client).post<AcknowledgeAlertResponses, AcknowledgeAlertErrors, ThrowOnError>({
		url: "/api/v1/alerts/{fingerprint}/acknowledge",
		...options,
	});
};

/**
 * Get config files that are in the config, but haven't been uploaded yet
 */
export const getRequiredFiles = <ThrowOnError extends boolean = false>(
	options?: Options<GetRequiredFilesData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<GetRequiredFilesResponses, GetRequiredFilesErrors, ThrowOnError>({
		url: "/api/v1/config/required-files",
		...options,
	});
};

/**
 * Upload an extra file required by the alertmanager spec
 */
export const postRequiredFiles = <ThrowOnError extends boolean = false>(
	options?: Options<PostRequiredFilesData, ThrowOnError>,
) => {
	return (options?.client ?? client).post<PostRequiredFilesResponses, PostRequiredFilesErrors, ThrowOnError>({
		url: "/api/v1/config/required-files",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Get a silence by ID
 */
export const getSilence = <ThrowOnError extends boolean = false>(options: Options<GetSilenceData, ThrowOnError>) => {
	return (options.client ?? client).get<GetSilenceResponses, GetSilenceErrors, ThrowOnError>({
		url: "/api/v2/silence/{id}",
		...options,
	});
};

/**
 * Get a list of silences
 */
export const getSilences = <ThrowOnError extends boolean = false>(options?: Options<GetSilencesData, ThrowOnError>) => {
	return (options?.client ?? client).get<GetSilencesResponses, GetSilencesErrors, ThrowOnError>({
		url: "/api/v2/silences",
		...options,
	});
};

/**
 * Add silences to the system
 */
export const postSilence = <ThrowOnError extends boolean = false>(options?: Options<PostSilenceData, ThrowOnError>) => {
	return (options?.client ?? client).post<PostSilenceResponses, PostSilenceErrors, ThrowOnError>({
		url: "/api/v2/silences",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Get an uploaded alertmanager config
 */
export const getConfig = <ThrowOnError extends boolean = false>(options?: Options<GetConfigData, ThrowOnError>) => {
	return (options?.client ?? client).get<GetConfigResponses, GetConfigErrors, ThrowOnError>({
		url: "/api/v1/config",
		...options,
	});
};

/**
 * Upload an Alertmanager config
 */
export const postConfig = <ThrowOnError extends boolean = false>(options?: Options<PostConfigData, ThrowOnError>) => {
	return (options?.client ?? client).post<PostConfigResponses, PostConfigErrors, ThrowOnError>({
		url: "/api/v1/config",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Get a flattened version of the routing tree
 */
export const getRoutingTree = <ThrowOnError extends boolean = false>(
	options?: Options<GetRoutingTreeData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<GetRoutingTreeResponses, GetRoutingTreeErrors, ThrowOnError>({
		url: "/api/v1/config/tree",
		...options,
	});
};

/**
 * get the details about a user
 */
export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>) => {
	return (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({
		url: "/api/v1/user/{userID}",
		...options,
	});
};

/**
 * Get a list of history events for alerts
 */
export const getAlertHistory = <ThrowOnError extends boolean = false>(
	options?: Options<GetAlertHistoryData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<GetAlertHistoryResponses, GetAlertHistoryErrors, ThrowOnError>({
		url: "/api/v1/alerts/{fingerprint}/history",
		...options,
	});
};

/**
 * Add a comment to an alert
 */
export const postAlertComment = <ThrowOnError extends boolean = false>(
	options: Options<PostAlertCommentData, ThrowOnError>,
) => {
	return (options.client ?? client).post<PostAlertCommentResponses, PostAlertCommentErrors, ThrowOnError>({
		url: "/api/v1/alerts/{fingerprint}/comment",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options.headers,
		},
	});
};

/**
 * Get all the API tokens for the authenticated user
 */
export const getUserTokens = <ThrowOnError extends boolean = false>(
	options?: Options<GetUserTokensData, ThrowOnError>,
) => {
	return (options?.client ?? client).get<GetUserTokensResponses, GetUserTokensErrors, ThrowOnError>({
		url: "/api/auth/tokens",
		...options,
	});
};

/**
 * Create a new API key for the authenticated user
 */
export const postApiKey = <ThrowOnError extends boolean = false>(options?: Options<PostApiKeyData, ThrowOnError>) => {
	return (options?.client ?? client).post<PostApiKeyResponses, PostApiKeyErrors, ThrowOnError>({
		url: "/api/auth/tokens",
		...options,
		headers: {
			"Content-Type": "application/json",
			...options?.headers,
		},
	});
};

/**
 * Delete an API key for the authenticated user
 */
export const deleteApiKey = <ThrowOnError extends boolean = false>(
	options: Options<DeleteApiKeyData, ThrowOnError>,
) => {
	return (options.client ?? client).delete<DeleteApiKeyResponses, DeleteApiKeyErrors, ThrowOnError>({
		url: "/api/auth/tokens/{tokenId}",
		...options,
	});
};
